### ISSUE TITLE
Multiple artifacts of the module com.google.inject#guice;4.0 are retrieved to the same file

### ISSUE THREAD

**Issue by luislozoya** [barry-allen07/FB-Mod#11]
Hello, I want to contribute to this project, but I'm having trouble compiling it 

Caffeine was giving me problems so I changed rev from 2.6.2 to 3.0.1

After that I run ant resolve again, and I got this error:

`BUILD FAILED
C:\Users\lozoy\Google Drive\java\JavaProjects\filebot mod\FB-Mod\build.xml:948: impossible to ivy retrieve: java.lang.RuntimeException: problem during retrieve of net.filebot#filebot: java.lang.RuntimeException: Multiple artifacts of the module com.google.inject#guice;4.0 are retrieved to the same file! Update the retrieve pattern  to fix this error.
        at org.apache.ivy.core.retrieve.RetrieveEngine.retrieve(RetrieveEngine.java:238)
        at org.apache.ivy.Ivy.retrieve(Ivy.java:561)
        at org.apache.ivy.ant.IvyRetrieve.doExecute(IvyRetrieve.java:113)
        at org.apache.ivy.ant.IvyTask.execute(IvyTask.java:259)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:827)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.lang.RuntimeException: Multiple artifacts of the module com.google.inject#guice;4.0 are retrieved to the same file! Update the retrieve pattern  to fix this error.
        at org.apache.ivy.core.retrieve.RetrieveEngine.determineArtifactsToCopy(RetrieveEngine.java:413)
        at org.apache.ivy.core.retrieve.RetrieveEngine.retrieve(RetrieveEngine.java:122)
        ... 19 more

Total time: 18 seconds
`

**Comment by RodBelaFarin** [comment]
I ran into exactly the same problem and don't know how to fix this.

**Comment by SHJordan** [comment]
D:/Animes/{ ~plex } naming scheme not working with this version.

**Comment by nsenica** [comment]
Retrieve pattern needs to be adjusted on build.xml:950 : 
`<ivy:retrieve pattern="${dir.lib}/ivy/[type]/[artifact](-[classifier]).[ext]" />`

It will work just fine.
