### ISSUE TITLE
REQUEST: Can you do a build for r6224

### ISSUE THREAD

**Issue by wicadmin** [barry-allen07/FB-Mod#7]
I have a groovy error running on r6120

```
No such property: license for class: Script1
groovy.lang.MissingPropertyException: No such property: license for class: Script1
        at Script1.run(Script1.groovy:14)
        at net.filebot.cli.ScriptShell.evaluate(ScriptShell.java:64)
        at net.filebot.cli.ScriptShell.runScript(ScriptShell.java:74)
        at net.filebot.cli.ArgumentProcessor.runScript(ArgumentProcessor.java:162)
        at net.filebot.cli.ArgumentProcessor.run(ArgumentProcessor.java:37)
        at net.filebot.Main.main(Main.java:129)

```
I am only using the portalble jar and I do not see build instructions for Linux. Do not have Windows or MacOS.

Thank you.

**Comment by wicadmin** [comment]
OK, I got pass this calling the script directly.

Anyway, good to know how to do this build.

TY.
